language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("MeshIO")); Pkg.add("Coverage"); Pkg.checkout("Coverage"); Pkg.checkout("Requests")'
- julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
